# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 陶思雨
email: taosiyu19@126.com
description: > # this means to ignore newlines until "baseurl:"
  这是一个博客，也是一个小站，分享编码心得，当然还有一些小众的推荐。。。敬请期待，期待后续的跟新
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

keep_files: [".git", ".nojekyll"]

#############
permalink: '/:title.html'

defaults:
  scope:
    path: ""
    type: "posts"
    values:
      layout: "post"

##############

# Build settings
markdown: kramdown

# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - package.json
  - gulpfile.js
  - node_modules

jekyll-archives:
  enabled: all
paginate_path: "page:num" 
paginate: 10
